log:
  level: DEBUG

api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    swarmMode: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: "flaviojunior1070@gmail.com"
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: web
