version: '3.8'

services:
  traefik:
    image: ${TRAEFIK_IMAGE}
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./../configs/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./../configs/middlewares.yml:/etc/traefik/middlewares.yml:ro
      - ./../secrets/acme.json:/letsencrypt/acme.json
    networks:
      - ${TRAEFIK_NETWORK}
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.traefik.rule=Host(`${TRAEFIK_DOMAIN}`)
        - traefik.http.routers.traefik.entrypoints=websecure
        - traefik.http.routers.traefik.service=api@internal
        - traefik.http.routers.traefik.tls.certresolver=letsencrypt
        - traefik.http.services.traefik.loadbalancer.server.port=8080
        - traefik.http.routers.traefik.middlewares=auth

networks:
  - traefik-public:
    external: true
