http:
  middlewares:
    auth:
      basicAuth:
        users:
          # - "admin:$$2b$$12$$hqPSl7WL0ldRiH08Gg3rHupQN/un2flJKeQ05tKYGwtqT8xuQPtBq"
          - "${TRAEFIK_DASHBOARD_USER}:${TRAEFIK_DASHBOARD_PASS_HASH}"
          
    security-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        stsSeconds: 63072000  # 2 anos

    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
